name: Frontend CI Deploy to Github Pages

on:
  push:
    branches:
      - 'main'
    paths: 
      - 'tix-angular-client/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Angular FE APP Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    timeout-minutes: 15

    concurrency:
      group: frontend-ci-${{ github.ref }}
      cancel-in-progress: true

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Create .env file for frontend'
        working-directory: tix-angular-client
        run: |
          touch .env
          echo PRODUCTION_ENVIRONMENT=true >> .env
          echo API_SERVER_URL=${{ vars.API_SERVER_URL }} >> .env
          cat .env

      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: ./tix-angular-client/node_modules
          key: tix-angular-client-${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/tix-angular-client/package-lock.json') }}
          restore-keys: |
            tix-angular-client-${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/tix-angular-client/package-lock.json'

      - name: Install dependencies (if node_modules cache not found)
        if: ${{ steps.cache-node-modules.outputs.cache-hit != 'true' }}
        working-directory: tix-angular-client
        run: npm ci

      - name: Update environment file variables
        working-directory: tix-angular-client
        run: npm run env

      - name: Build
        working-directory: tix-angular-client
        run: npm run build -- --configuration production

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './tix-angular-client/dist/tix-client/browser/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
